[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d -s -t"
# runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv8m.main-none-eabihf"    # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
